DROP TABLE IF EXISTS todo_tags;
DROP TABLE IF EXISTS todos;
DROP TYPE IF EXISTS todo_priority;
DROP TYPE IF EXISTS todo_status;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
